version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
    working_directory: ~/blog

    steps:
      - checkout
      - run: gem install bundler jekyll
      - run: bundle install
      - run: bundle exec jekyll build
      - run: ls

workflows:
  version: 2
  workflow:
    jobs:
        - build