version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
    working_directory: ~/blog

    steps:
      - checkout
      - run: gem install bundler jekyll

workflows:
  version: 2
  workflow:
    jobs:
        - build