version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.0-node
        environment:
          BUNDLER_VERSION: 2.0.1
    working_directory: ~/blog

    steps:
      - checkout
      - run: gem install bundler jekyll
      - run: bundle install
      - run: bundle exec jekyll build
      - run: git push <remote_name> --delete <branch_name>

workflows:
  version: 2
  workflow:
    jobs:
        - build